[compiler.solc]
exclude_paths = [".venv", "venv", "lib", "script", "test", "node_modules"]
remappings = [
    "@symbioticfi/core/=lib/core/",
    "@openzeppelin/contracts-upgradeable/=lib/core/lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/core/lib/openzeppelin-contracts/contracts/",
    "burners/=lib/burners/",
    "core/=lib/core/",
    "ds-test/=lib/core/lib/openzeppelin-contracts-upgradeable/lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=lib/core/lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts-upgradeable/=lib/core/lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/core/lib/openzeppelin-contracts/",
]
via_IR = true
target_version = "0.8.25"

[compiler.solc.optimizer]
enabled = false
runs = 200

[compiler.solc.metadata]
append_CBOR = true
use_literal_content = false
bytecode_hash = "ipfs"

[detectors]
exclude = []
ignore_paths = [".venv", "venv", "test"]
exclude_paths = [".venv", "venv", "lib", "script", "test", "node_modules"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent --disable-code-size-limit"
# cmd_args = "--fork-url  --fork-block-number 22698495 --fork-chain-id 1 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""
